---
version: 2

workflows:
  version: 2
  build_linux:
    jobs:
      - pigen

jobs:
  pigen:
    working_directory: ~/work
    machine:
      image: circleci/classic:latest
    # docker:
    #  - image: debian:stretch

    steps:
      - checkout
      - run: sudo apt update &&
          sudo apt install -y --no-install-recommends
            quilt parted realpath qemu-user-static debootstrap zerofree pxz zip
            dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl
            openssl ca-certificates git sudo bc wget rsync

      - run: git clone https://github.com/RPi-Distro/pi-gen
      - run: pwd; ls -al; id -a
      # add ToxBlinkenwall custom build stuff ----------
      - run: cd ./stage2 ; find . -name '*.sh' -exec chmod a+x {} \;
      - run: cd ./stage2 ; ls -alR
      - run: cp -av ./stage2 pi-gen/
      # give name of current branch to docker
      - run: mkdir -p ~/work/pi-gen/work/ ; echo "$CIRCLE_BRANCH" > ~/work/pi-gen/work/_GIT_BRANCH_
      - run: echo "$CIRCLE_BRANCH"; cat ~/work/pi-gen/work/_GIT_BRANCH_
      # add ToxBlinkenwall custom build stuff ----------
      - run: cd pi-gen;echo "IMG_NAME='Raspbian'" > config
      - run: cd pi-gen;touch ./stage3/SKIP ./stage4/SKIP ./stage5/SKIP
      - run: cd pi-gen;touch ./stage4/SKIP_IMAGES ./stage5/SKIP_IMAGES
      - run: cd pi-gen;sudo ./build-docker.sh # ./build.sh
      - run: cd pi-gen; ls -hal deploy/
      - run: cd pi-gen; mkdir -p deploy2/
      - run: cd pi-gen; cp -av deploy/image_*-Raspbian-lite.zip deploy2/image-Raspbian-lite.zip
      - run: cd pi-gen; cp -av deploy/build.log deploy2/
      - run: cd pi-gen; ls -hal deploy2/

      - store_artifacts:
          path: ~/work/pi-gen/deploy2
          destination: deploy


